# =============================================
# BNR Payment Service - Configuration
# =============================================

server.port=8082
spring.application.name=payment-service

# =============================================
# Database (PostgreSQL / Supabase)
# =============================================
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.jpjsyscngkefoupmggkw
spring.datasource.password=Urujeni0005@!@!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =============================================
# RabbitMQ
# =============================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# =============================================
# Logging
# =============================================
logging.level.com.bnr=DEBUG
logging.level.org.springframework.amqp=INFO